# Dev-окружение: расширенное логирование, debug-уровень
logging.level.com.example.currency-rate-provider=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=TRACE

# В dev можно использовать упрощённые настройки
rate.base=80.0
rate.variation=2.0